### ISSUE TITLE
try making the games compatible arrays so if a plugin is compatible with more than 1 game you don't ahve the plugin twice.

### ISSUE THREAD

**Issue by martinmontane** [OctoNezd/NTRDB#9] opened 2017-02-16 18:22 UTC
title

**Comment by OctoNezd** [comment] 2017-02-17 05:44
You mean multiple TitleIDs? I dont think it is a good idea..

**Comment by OctoNezd** [comment] 2017-02-17 06:11
Duplicate of #8

**Closed by OctoNezd** 2017-02-17 06:11 UTC
